### ISSUE TITLE
Domain layer entities need to be parcelable

### ISSUE THREAD

**Issue by akshaybhange** [antoniolg/clean-architecture#1]
HI @antoniolg, great work. I wanted to know domain layer entities are needed to be parcelable in order to pass between activities/fragments. But when we declare them parcelable we will need to convert this module from "java-library" to android library or something. How to handle this case. You don't need that in this case but please help me solve this issue.

**Comment by antoniolg** [comment]
No, in that case, you need to create models in the presentation layer, and do conversions between layers using data mappers. Domain models shouldn't know anything about parcelables, or Room (in case you save it to a database), or Json (in case you parse it from the server)... All that needs to be transformed between layers.

**Comment by akshaybhange** [comment]
@antoniolg  thanks, I have entities at framework level for Server responses & models at domain level can I use any of it for my use in presentation layer or do I have to create new ones for presentation layer only? If you have any article on data mappers (the easy & correct way) please provide that too.

**Comment by JulienHivert** [comment]
Hello
Let me reopen the topic, because I am currently in the middle of an architectural realignment of a big project (passed from hand to hand). Being in the same situation as @akshaybhange on my Parcelable data class. From what I understand from your exchanges it is that it is necessary (for parcelable objects) to map from the domain layer to presentation. I would like to enlarge the question: Do we have to map ALL the objects between domain and presentation? Is this a good practice?
Sincerely 

Translated with www.DeepL.com/Translator (free version)

**Comment by JulienHivert** [comment]
Hello ! :D 
Let me reopen the topic, because I am currently in the middle of an architectural realignment of a big project (passed from hand to hand). Being in the same situation as @akshaybhange on my Parcelable data class. From what I understand from your exchanges it is that it is necessary (for parcelable objects) to map from the domain layer to presentation. I would like to enlarge the question: Do we have to map ALL the objects between domain and presentation? Is this a good practice?
Sincerely

**Comment by antoniolg** [comment]
I don't think it's strictly necessary, only when it's required. But if you do it, it's not bad either.
